<?php
//Barra de progresso do cadastro
$this->stepBar();
?>

<div class="row rowDadosPess rowDadosForm" id="rowForm">
    <!-- Painel -->
    <div class="panel-form panel-form-home">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-lock"></span> Avise-me sobre promoções de passagens</div>
            <div class="panel-body">
                <h3>Preencha os seus dados</h3>

                <!-- Formulaário -->
                <form class="form-horizontal form-complemento-cadastro" role="form" method="post" action="/usuario/validar-telefone">
                    <!-- Usuário cadastrado -->
                    <div class="form-group form-rad dvCampoPossuiCadastro">
                        <div class="col-sm-10 dvRadIda">
                            <input type="radio" name="radNovoUsuario" id="radNovoUsuario" checked="true" value=1> <label for="radNovoUsuario">Gostaria de me cadastrar</label>
                            <input type="radio" name="radNovoUsuario" id="radUsuarioCadastrado" value=2> <label for="radUsuarioCadastrado">Já sou cadastrado</label>
                        </div>
                    </div>
                    <!-- Telefone -->
                    <div class="form-group dvCampoTel">
                        <label for="inputTel" class="control-label">Telefone <img src="/img/ajax-loader.gif" class="telAjax" style="display:none" /></label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control bfh-phone inputTel" name="tel"
                                   id="inputTel" required placeholder="Telefone com DDD"
                                   value="<?php echo isset($this->dataForm['tel']) ? $this->dataForm['tel'] : '' ?>">
                        </div>
                    </div>
                    <!-- Email -->
                    <div class="form-group dvCampoEmail">
                        <label for="inputEmail" class="control-label">Email</label>
                        <div class="col-sm-10">
                            <input type="email" class="form-control" placeholder="Insira o seu email" name="email" required
                                   value="<?php echo isset($this->dataForm['email']) ? $this->dataForm['email'] : '' ?>"
                                   maxlength="200">
                        </div>
                    </div>
                    <div class="clear"></div>
                    <!-- Senha -->
                    <div class="form-group dvCampoSenha">
                        <label for="inputSenha" class="control-label">Senha</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="inputSenha" 
                                   required maxlength="10" placeholder="Senha" name="senha">
                        </div>
                    </div>
                    <!-- Confirma da Senha -->
                    <div class="form-group dvConfSenha dvCampoSenha">
                        <label for="inputSenhaConf" class="control-label">Confirme a Senha</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="inputSenhaConf" 
                                   required maxlength="10" placeholder="Confirmação da senha"
                                   name="conf_senha">
                        </div>
                    </div>
                    <div class="clear"></div>
                    <br />
                    <div class="form-group">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-success btn-sm">Avançar</button>
                            <button type="reset" class="btn btn-default btn-sm btn-voltar">Voltar</button>
                        </div>
                    </div>
                </form>

            </div>
            <div class="panel-footer">
                <a href="/"></a>
            </div>
        </div>
    </div>
</div>

<?php
//Coluna da direita
$this->colRight();
?>


<script type="text/javascript">
    $(document).ready(function() {
        //Inicia a variável 
        var telefone = null;
        
        <?php
            //Seta o id do usuário já cadastrado
            if( isset($this->dataForm['id_usuario']) ) {
                echo "var id_usuario = " . $this->dataForm['id_usuario'] . ";\n";
                echo "telefone = '" . $this->dataForm['tel'] . "';\n";
            }
        ?>
        
        var telValido = false;
        var inAjax = false;
        
        //Carrega as máscaras e plugins dos campos
        carregarMascaras();

        //Volta para a página anterior
        $(".btn-voltar").click(function() {
            window.location = '/usuario/dados-voo';
        });

        //Submet o formulário
        $(".form-complemento-cadastro").submit(function() {
            if( inAjax ) {
                return false;
            }
            if( !telValido ) {
                msgTelefoneExistente();
                return false;
            }
            
            //Valida as senhas
            if ($("#inputSenha").val() != $("#inputSenhaConf").val()) {
                setNotification("As senhas devem ser iguais!", 'warning');
                return false;
            }
        });

        //Verifica se o telefone já foi cadastrado
        $("#inputTel").blur(function() {
            atualizarFlagTelefoneCadastrado($(this));
        });
        function atualizarFlagTelefoneCadastrado(objField) {
            inAjax = true;
            $(".telAjax").show();
            
            $.ajax({
                url: "/usuario/consultar-tel",
                type: "post",
                async: false,
                dataType: "json",
                data: {tel:objField.val()},
                success: function(rs) {
                    if (rs.return == true) {
                        //Verica se o telefone já foi cadastrado e se o mesmo não é de propriedade do usuário
                        telValido = validarTelefone();
                    } else {
                        telValido = true;
                    }
                    inAjax = false;
                    $(".telAjax").hide();
                }
            });
        }
        atualizarFlagTelefoneCadastrado($("#inputTel"));
        
        //Exibe a mensagem de telefone existente
        function msgTelefoneExistente() {
            setNotification("O telefone informado já está cadastrado!", 'warning');
        }
        
        //Valida se o telefone já foi cadastrado
        function validarTelefone() {
            if( !telefone || (telefone && telefone != $("#inputTel").val()) ) {
                msgTelefoneExistente();
                return false;
            }
            
            return true;
        }
        
        //Exibe/Oculta o campo de confirmação de senha
        $("input[name=radNovoUsuario]").change(function() {
            if ($(this).val() == 2) {
                $("div.dvConfSenha input").attr('disabled', 1);
                $("div.dvConfSenha").hide();
            } else {
                $("div.dvConfSenha input").removeAttr('disabled');
                $("div.dvConfSenha").show();
            }
        });
        $("input[name=radNovoUsuario]:checked").change();
    });
</script>