<?php
//Barra de progresso do cadastro
$this->stepBar();
?>

<div class="row rowDadosPess rowDadosForm" id="rowForm">
    <!-- Painel -->
    <div class="panel-form panel-form-home">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Cadastro realizado com sucesso</h3>

                <p class="msg">Obrigado por se cadastrar no AviseMe. Em breve enviaremos avisos com promoções de passagens aéreas que se atendam a sua solicitação.</p>
                <br />
                
                <!-- Formulaário -->
                <form class="form-horizontal form-complemento-cadastro" role="form" method="post" action="/usuario/finalizar-cadastro">
                    <div class="clear"></div>
                    <br />
                    <div class="form-group">
                        <div class="col-sm-10">
                            <button type="button" class="btn btn-success btn-sm">Finalizar</button>
                        </div>
                    </div>
                </form>

            </div>
            <div class="panel-footer">
                <a href="/"></a>
            </div>
        </div>
    </div>
</div>

<?php
//Coluna da direita
$this->colRight();
?>


<script type="text/javascript">
    $(document).ready(function() {
        //Volta para a página anterior
        $(".btn-voltar").click(function() {
            window.location = '/usuario/dados-pessoais';
        });
    });
</script>