<div class="row" id="rowHomeForm">

    <!-- Container Img -->
    <div class="panel-img-home">
        <img src="/img/cover-home.png" />
    </div>

    <!-- Conteúdo -->
    <div class="panel-conteudo-home">
        <p>Fique por dentro de todas as promoções de passagens aéreas para os seus destinos preferidos.</p>
        <p>Com o Avise-ME você é informado via SMS sempre que uma passagem do seu interesse estiver dentro do preço acessível.</p>
    </div>

    <!-- Formulário -->
    <?php echo $this->render("/usuario/dados-voo.phtml"); ?>
</div>