<?php
//Barra de progresso do cadastro
$this->stepBar();
?>

<div class="row rowDadosPess rowDadosForm" id="rowForm">
    <!-- Painel -->
    <div class="panel-form panel-form-home">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Informe o código de validação</h3>

                <p class="msg">Foi enviado um código de validação para o seu celular. Insira o código no campo abaixo para continuar o cadastro.</p>
                <p class="msg2">* O envio do SMS pode levar alguns minutos. Caso a demora seja maior do que a prevista, continue o cadastro posteriormente através do link enviado para o seu email.</p>
                <br />
                
                <!-- Formulaário -->
                <form class="form-horizontal form-complemento-cadastro" role="form" method="post" action="/usuario/finalizar-cadastro">

                    <!-- Codigo -->
                    <div class="form-group dvCampoTel">
                        <label for="inputTel" class="control-label">Código</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="codigo" maxlength="4" required>
                        </div>
                    </div>
                    
                    <div class="clear"></div>
                    <br />
                    <div class="form-group">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-success btn-sm">Avançar</button>
                            <button type="reset" class="btn btn-default btn-sm btn-voltar">Voltar</button>
                        </div>
                    </div>
                </form>

            </div>
            <div class="panel-footer">
                <a href="/"></a>
            </div>
        </div>
    </div>
</div>

<?php
//Coluna da direita
$this->colRight();
?>


<script type="text/javascript">
    $(document).ready(function() {
        //Volta para a página anterior
        $(".btn-voltar").click(function() {
            window.location = '/usuario/dados-pessoais';
        });
    });
</script>