<!--Currency Converter widget by FreeCurrencyRates.com -->
<style>
.gcw_main2347286464{width:230px;font-family:Trebuchet MS,Tahoma,Verdana,Arial,sans-serif;font-size:11px;border:#A6C9E2 1px solid;text-align:center;color:#000000;background-color:#FCFDFD;margin:0 auto;}
.gcw_header2347286464{margin:4px;padding:5px;text-align:center;border:#4297D7 1px solid;background-color:#5C9CCC;}
#ccw_cnhfybwf2347286464{text-decoration:none;color:#FFFFFF;font-size:13px;font-weight:bold;}
.gcw_input2347286464{color:#2E6E9E;font-weight:bold;background-color:#FCFDFD;border:#C5DBEC 1px solid;text-align:right;padding:2px 0;margin:1px 0;display:inline;font-size:11px;}
.gcw_select2347286464{color:#000;display:inline;}
#gcw_date2347286464{font-size:10px;color:#2E6E9E;}
</style>
<div class="colRight">
    <div class="widConversao">
        <div class='gcw_main2347286464'><div class='gcw_header2347286464'><a href='http://www.freecurrencyrates.com/pt/myconverter#cur=BRL-USD-EUR-CAD-AUD-CNY-GBP-JPY-CHF-RUB;amt=BRL1' id='ccw_cnhfybwf2347286464'>Conversor de moeda</a></div><div id='gcw_rates2347286464'></div><script src='http://www.freecurrencyrates.com/converter-widget?source=cbr&width=230&currs=BRL,USD,EUR,CAD,AUD,CNY,GBP,JPY,CHF,RUB&precision=2&language=pt&flags=1&currchangable=0&firstrowvalue=1&id=2347286464' charset='UTF-8'></script></div>
        <!--End of Currency Converter widget by FreeCurrencyRates.com -->
    </div>
</div>