<?php

    /**
     * Monta as etapas do cadastro
     */

    $steps = array(
        array(
            'label' => '1) <span>Escolha seu voo</span>',
            'link' => '/usuario/dados-voo'
        ),
        array(
            'label' => '2) <span>Preencha seus dados</span>',
            'link' => '/usuario/dados-pessoais'
        ),
        array(
            'label' => '3) <span>Valide o seu telefone</span>',
            'link' => '/usuario/validar-telefone'
        ),
        array(
            'label' => '4) <span>Finalizar</span>',
            'link' => '/usuario/finalizar-cadastro'
        )
    );
    
    $front = Zend_Controller_Front::getInstance();
    $currentLink = "/" . $front->getRequest()->getControllerName() . "/" . $front->getRequest()->getActionName();
    
?>

<div id="dvStepBar">
    <div class="title">Cadastro</div>
    <ul id="ulStepBar">
        <?php 
            foreach($steps as $step){ 
                $class = ($step['link'] == $currentLink) ? "current" : "";
                echo "<li class='{$class}'>{$step['label']}</li>";
            }
        ?>
    </ul>
</div>